# Source: https://github.com/detekt/detekt/blob/62083e443d10861c8ab45b6bce6b97b917b24735/detekt-core/src/main/resources/default-detekt-config.yml#L4
# Source for KTLint rules: https://github.com/detekt/detekt/blob/62083e443d10861c8ab45b6bce6b97b917b24735/detekt-formatting/src/main/resources/config/config.yml#L4
build:
  excludeCorrectable: false

output-reports:
  active: true
  exclude:
    - 'TxtOutputReport'
    - 'MdOutputReport'
    - 'SarifOutputReport'
    - 'XmlOutputReport'

complexity:
  LongMethod:
    active: false
  LongParameterList:
    active: false
    functionThreshold: 8
  TooManyFunctions:
    active: false
  LargeClass:
    excludes: [ '**/test/**' ]
  CyclomaticComplexMethod:
    ignoreAnnotated:
      - Composable

naming:
  FunctionNaming:
    ignoreAnnotated: [ 'Composable' ]
  InvalidPackageDeclaration:
    active: false
  MatchingDeclarationName:
    active: false

potential-bugs:
  IgnoredReturnValue:
    active: false

exceptions:
  TooGenericExceptionCaught:
    active: false

performance:
  SpreadOperator:
    active: false

style:
  ForbiddenComment:
    active: false
  MagicNumber:
    active: false
    ignoreAnnotated:
      - 'Preview'
      - 'DevicePreview'
      - 'DevicePreviewNoSystemUi'
      - 'Composable'
  MaxLineLength:
    active: false
  ReturnCount:
    max: 3
  UnusedPrivateMember:
    active: false
  UnusedPrivateProperty:                                      # TODO: enable on a project
    active: false
  UnusedParameter:                                            # TODO: enable on a project
    active: false
  UnnecessaryAbstractClass:
    ignoreAnnotated:
      - 'Module'
  DestructuringDeclarationWithTooManyEntries:
    maxDestructuringEntries: 5

formatting:
  android: true
  AnnotationOnSeparateLine:
    active: false
  SpacingBetweenDeclarationsWithAnnotations:
    active: false
  MaximumLineLength:
    maxLineLength: 140
  Filename:
    active: false
